services:

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - "./var/log/nginx:/var/log/nginx"
      - ./:/var/www/symfony
      - ./docker/nginx/data/certs:/etc/nginx/certs
    depends_on:
      - symfony_app
      - postgres

  symfony_app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: symfony_app
    hostname: symfony_app
    restart: unless-stopped
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./var/log/php:/var/log/php"
      - ./:/var/www/symfony
    working_dir: /var/www/symfony

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_DATA}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgvolume:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgvolume: